FROM python:3.12-slim AS builder

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir --user -r requirements.txt \
    && pip install --no-cache-dir --user uvicorn


FROM python:3.12-slim AS runner

WORKDIR /app


COPY --from=builder /root/.local /root/.local

COPY . .


ENV PATH=/root/.local/bin:$PATH

EXPOSE 5000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]